# Generated by Django 6.0.5 on 2026-05-26 20:30

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeasModel',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('admin_action', models.CharField(choices=[('Pending', 'Pending'), ('under_review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=25)),
                ('submission_id', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('institution_or_college', models.CharField(max_length=255)),
                ('course_or_field_of_study', models.CharField(max_length=255)),
                ('type_of_idea', models.CharField(blank=True, choices=[('Innovation', 'Innovation Idea'), ('Business', 'Business Idea')], max_length=20, null=True)),
                ('title_of_idea', models.CharField(blank=True, max_length=255, null=True)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('solution_description', models.TextField(blank=True, null=True)),
                ('target_users', models.TextField(blank=True, null=True)),
                ('uniqueness_of_the_idea', models.TextField(blank=True, null=True)),
                ('implementation_plan', models.TextField(blank=True, null=True)),
                ('estimated_cost_to_start', models.CharField(blank=True, max_length=255, null=True)),
                ('potential_market', models.TextField(blank=True, null=True)),
                ('expected_impact', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('prototype_picture', models.ImageField(blank=True, null=True, upload_to='prototypeImages/')),
                ('diagram', models.ImageField(blank=True, null=True, upload_to='diagrams/')),
                ('current_step', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
