# Generated by Django 6.0.5 on 2026-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideasmodel',
            old_name='admin_action',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='current_step',
            field=models.IntegerField(default=1, help_text='User tracking steps '),
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='if user complete to fill a form or not'),
        ),
    ]
