# Generated by Django 6.0.5 on 2026-05-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_rename_admin_action_ideasmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasmodel',
            name='estimated_cost_to_start',
            field=models.CharField(blank=True, help_text='For Innovation idea is null/empty', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='expected_impact',
            field=models.TextField(blank=True, help_text='For Innovation idea is null/empty', null=True),
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='potential_market',
            field=models.TextField(blank=True, help_text='For Innovation idea is null/empty', null=True),
        ),
    ]
