# Generated by Django 6.0.5 on 2026-05-27 15:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_alter_ideasmodel_estimated_cost_to_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasmodel',
            name='diagram',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='document',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload PDF or Word Documents', max_length=255, null=True, verbose_name='document'),
        ),
        migrations.AlterField(
            model_name='ideasmodel',
            name='prototype_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
