# Generated by Django 6.0.5 on 2026-05-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_alter_ideasmodel_diagram_alter_ideasmodel_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideasmodel',
            name='diagram',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='document',
        ),
        migrations.RemoveField(
            model_name='ideasmodel',
            name='prototype_picture',
        ),
    ]
